# Generated by Django 2.0 on 2017-12-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entradas',
        ),
        migrations.DeleteModel(
            name='Saidas',
        ),
    ]
